[General]
SyntaxVersion=2
BeginHotkey=112
BeginHotkeyMod=4
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=bb1231fb-2845-4acf-b409-36980c99cf8a
Description=路径v1
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 730, 820
MoveTo 815, 826
Delay 2189
LeftDown 1
Delay 27
LeftDown 1
Delay 1142
LeftUp 1
Delay 3
LeftUp 1
Delay 3617
KeyDown "Down", 1
Delay 7
Delay 126
KeyUp "Down", 1
Delay 8
Delay 150
KeyDown "Down", 1
Delay 5
Delay 91
KeyUp "Down", 1
Delay 4
Delay 122
KeyDown "Down", 1
Delay 7
Delay 70
KeyUp "Down", 1
Delay 7
MoveTo 879, 381
Delay 975
LeftDown 1
Delay 5
LeftClick 1
Delay 2
LeftUp 1
MoveTo 987, 730
Delay 1292
LeftDown 1
Delay 7
LeftClick 1
Delay 4
LeftUp 1
MoveTo 936, 649
Delay 1039
KeyDown "Space", 1
Delay 109
KeyUp "Space", 1
MoveTo 923, 565
Delay 1519
LeftDown 1
Delay 5
LeftDown 1
Delay 5
LeftDown 1
Delay 7
LeftDown 1
Delay 4
LeftDown 1
Delay 5
LeftDown 1
Delay 123
LeftDown 1
Delay 6
LeftClick 1
Delay 5
LeftUp 1
MoveTo 1210, 341
Delay 3329
LeftDown 1
Delay 4
LeftClick 1
Delay 2
LeftUp 1
MoveTo 926, 574
Delay 1407
LeftDown 1
Delay 7
LeftClick 1
Delay 3
LeftUp 1
MoveTo 691, 647
Delay 1487
LeftDown 1
Delay 4
LeftClick 1
Delay 2
LeftUp 1
MoveTo 797, 644
Delay 722
LeftDown 1
Delay 4
LeftClick 1
Delay 3
LeftUp 1
Delay 2
LeftUp 1
Delay 412
KeyDown "Space", 1
Delay 130
KeyUp "Space", 1
MoveTo 681, 439
Delay 1216
LeftDown 1
Delay 5
LeftClick 1
Delay 5
LeftUp 1
MoveTo 705, 650
Delay 706
LeftDown 1
Delay 4
LeftClick 1
Delay 5
LeftUp 1
MoveTo 810, 650
Delay 580
LeftDown 1
Delay 4
LeftClick 1
Delay 4
LeftUp 1
Delay 695
KeyDown "Space", 1
Delay 4
Delay 3
KeyDown "Space", 1
Delay 3
Delay 3
KeyDown "Space", 1
Delay 3
Delay 131
KeyDown "Space", 1
MoveTo 811, 650
Delay 8
KeyUp "Space", 1
MoveTo 1181, 648
Delay 693
LeftDown 1
Delay 4
LeftClick 1
Delay 3
LeftUp 1
MoveTo 1214, 337
Delay 1295
LeftDown 1
Delay 4
LeftClick 1
Delay 3
LeftUp 1
MoveTo 899, 577
Delay 1516
LeftDown 1
Delay 5
LeftClick 1
Delay 5
LeftUp 1
MoveTo 692, 651
Delay 1783
LeftDown 1
Delay 5
LeftDown 1
Delay 5
LeftDown 1
Delay 8
LeftDown 1
Delay 4
LeftDown 1
Delay 5
LeftDown 1
Delay 122
LeftDown 1
Delay 10
LeftClick 1
Delay 2
LeftUp 1
MoveTo 824, 647
Delay 682
LeftDown 1
Delay 4
LeftClick 1
Delay 3
LeftUp 1
MoveTo 815, 639
Delay 497
KeyDown "Space", 1
Delay 111
KeyUp "Space", 1
MoveTo 667, 442
Delay 1357
LeftDown 1
Delay 5
LeftDown 1
Delay 7
LeftDown 1
Delay 5
LeftDown 1
Delay 5
LeftDown 1
Delay 6
LeftDown 1
Delay 122
LeftDown 1
Delay 6
LeftClick 1
Delay 3
LeftUp 1
MoveTo 698, 653
Delay 805
LeftDown 1
Delay 4
LeftClick 1
Delay 3
LeftUp 1
MoveTo 813, 651
Delay 649
LeftDown 1
Delay 4
LeftClick 1
Delay 2
LeftUp 1
MoveTo 818, 654
Delay 1036
KeyDown "Space", 1
Delay 5
Delay 4
KeyDown "Space", 1
Delay 3
Delay 3
KeyDown "Space", 1
Delay 3
Delay 131
KeyDown "Space", 1
Delay 4
KeyUp "Space", 1
MoveTo 1171, 648
Delay 967
LeftDown 1
Delay 4
LeftClick 1
Delay 2
LeftUp 1
MoveTo 1204, 337
Delay 1113
LeftDown 1
Delay 4
LeftClick 1
Delay 3
LeftUp 1
MoveTo 893, 573
Delay 1309
LeftDown 1
Delay 4
LeftClick 1
Delay 4
LeftUp 1
MoveTo 687, 652
Delay 1127
LeftDown 1
Delay 7
LeftClick 1
Delay 3
LeftUp 1
MoveTo 796, 648
Delay 1055
LeftDown 1
Delay 6
LeftClick 1
Delay 3
LeftUp 1
MoveTo 820, 647
Delay 338
KeyDown "Space", 1
Delay 99
KeyUp "Space", 1
MoveTo 668, 438
Delay 784
LeftDown 1
Delay 5
LeftClick 1
Delay 2
LeftUp 1
MoveTo 698, 648
Delay 1229
LeftDown 1
Delay 8
LeftDown 1
Delay 4
LeftDown 1
Delay 6
LeftDown 1
Delay 4
LeftDown 1
Delay 5
LeftDown 1
Delay 118
LeftDown 1
Delay 4
LeftClick 1
Delay 4
LeftUp 1
MoveTo 820, 648
Delay 403
LeftDown 1
Delay 5
LeftClick 1
Delay 3
LeftUp 1
MoveTo 832, 649
Delay 359
KeyDown "Space", 1
Delay 122
KeyUp "Space", 1
MoveTo 1188, 648
Delay 1704
LeftDown 1
Delay 4
LeftDown 1
Delay 3
LeftDown 1
Delay 6
LeftDown 1
Delay 4
LeftDown 1
Delay 4
LeftDown 1
Delay 124
LeftDown 1
Delay 9
LeftClick 1
Delay 2
LeftUp 1
MoveTo 1041, 615
Delay 2745
KeyPress Right, 1
KeyPress Space, 1
LeftDown 1
Delay 6
LeftDown 1
Delay 4
LeftDown 1
Delay 5
LeftDown 1
Delay 5
LeftDown 1
Delay 5
LeftDown 1
Delay 122
LeftClick 1
MoveTo 1221, 341
Delay 753
LeftDown 1
Delay 3
LeftClick 1
Delay 2
LeftUp 1
MoveTo 896, 578
Delay 2590
LeftDown 1
Delay 5
LeftClick 1
Delay 4
LeftUp 1
MoveTo 691, 644
Delay 2233
LeftDown 1
Delay 4
LeftDown 1
Delay 7
LeftDown 1
Delay 4
LeftDown 1
Delay 5
LeftDown 1
Delay 6
LeftDown 1
Delay 121
LeftDown 1
Delay 5
LeftClick 1
Delay 4
LeftUp 1
MoveTo 811, 650
Delay 542
LeftDown 1
Delay 4
LeftClick 1
Delay 3
LeftUp 1
Delay 3
LeftUp 1
Delay 385
KeyDown "Space", 1
Delay 124
KeyUp "Space", 1
MoveTo 660, 436
Delay 769
LeftDown 1
Delay 4
LeftClick 1
Delay 3
LeftUp 1
MoveTo 679, 646
Delay 1042
LeftDown 1
Delay 6
LeftClick 1
Delay 2
LeftUp 1
MoveTo 812, 644
Delay 1652
LeftDown 1
Delay 5
LeftClick 1
Delay 3
LeftUp 1
Delay 734
KeyDown "Space", 1
Delay 4
Delay 3
KeyDown "Space", 1
Delay 6
Delay 2
KeyDown "Space", 1
Delay 3
Delay 127
KeyDown "Space", 1
Delay 5
KeyUp "Space", 1
MoveTo 1176, 651
Delay 969
LeftDown 1
Delay 7
LeftClick 1
Delay 3
LeftUp 1
MoveTo 1220, 337
Delay 1870
LeftDown 1
Delay 7
LeftClick 1
Delay 4
LeftUp 1
MoveTo 922, 575
Delay 1071
LeftDown 1
Delay 5
LeftClick 1
Delay 7
LeftUp 1
MoveTo 683, 646
Delay 1648
LeftDown 1
Delay 5
LeftClick 1
Delay 2
LeftUp 1
MoveTo 805, 647
Delay 239
LeftDown 1
Delay 6
LeftClick 1
Delay 2
LeftUp 1
Delay 359
KeyDown "Space", 1
Delay 121
KeyUp "Space", 1
MoveTo 661, 439
Delay 856
LeftDown 1
Delay 5
LeftClick 1
Delay 3
LeftUp 1
MoveTo 698, 651
Delay 1117
LeftDown 1
Delay 8
LeftClick 1
Delay 6
LeftUp 1
MoveTo 820, 648
Delay 153
LeftDown 1
Delay 5
LeftClick 1
Delay 5
LeftUp 1
Delay 334
KeyDown "Space", 1
Delay 99
KeyUp "Space", 1
MoveTo 1191, 647
Delay 1423
LeftDown 1
Delay 4
LeftClick 1
Delay 4
LeftUp 1
MoveTo 1273, 275
Delay 2216
LeftDown 1
Delay 3
LeftDown 1
Delay 507
LeftUp 1
'==========以上是按键精灵录制的内容==========
